sudo: false

language: ruby

rvm:
  - 2.4.0

cache: bundler

script: bundle exec middleman build

deploy:
  skip_cleanup: true
  provider: surge
  domain: wye-api.surge.sh
  on: master
  project: ./build/
