sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

cache: bundler

script: bundle exec middleman build

deploy:
  provider: surge
  domain: wye-api.surge.sh
  on: master
  # This `skip_cleanup` is important, as it prevents TravisCI to cleanup the files
  # generated in the `build` folder by the `script:` section above...
  skip_cleanup: true
  # ...which can then be deployed to surge.sh from this `build` folder.
  project: ./build/
  - 2.4.0
